apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: connect-h1
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "connect",
      "pod-name": "h1",
      "interface": {
        "items": [
          {
            "name": "net1",
            "target-pod-name": "r1",
            "target-pod-nic": "net1",
            "self-tunnel-id": "1",
            "target-tunnel-id": "2",
            "session-id": "1"
          }
        ]
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: connect-h2
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "connect",
      "pod-name": "h2",
      "interface": {
        "items": [
          {
            "name": "net1",
            "target-pod-name": "r1",
            "target-pod-nic": "net2",
            "self-tunnel-id": "3",
            "target-tunnel-id": "4",
            "session-id": "2"
          }
        ]
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: connect-r1
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "connect",
      "pod-name": "r1",
      "interface": {
        "items": [
          {
            "name": "net1",
            "target-pod-name": "h1",
            "target-pod-nic": "net1",
            "self-tunnel-id": "2",
            "target-tunnel-id": "1",
            "session-id": "1"
          },
          {
            "name": "net2",
            "target-pod-name": "h2",
            "target-pod-nic": "net1",
            "self-tunnel-id": "4",
            "target-tunnel-id": "3",
            "session-id": "2"
          }
        ]
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: h1-net1
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "h1-net1",
      "ipam": {
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: h2-net1
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "h2-net1",
      "ipam": {
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: r1-net1
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "r1-net1",
      "ipam": {
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: r1-net2
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "r1-net2",
      "ipam": {
      }
    }
---
apiVersion: v1
kind: Pod
metadata: 
  name: h1
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "h1-net1"},
      {"name": "connect-h1"}
    ]'
spec: 
  containers:
  - name: h1
    image: sugaott/sugaott-ubuntu-focal:1.4
    command: ["bash", "-c", "sleep infinity"]
    securityContext:
      privileged: true
    lifecycle:
          postStart:
            exec:
              command:
                - sh
                - -c
                - "ip link set eth0 down; ip addr add 192.168.0.2/24 dev net1; ip route add default via 192.168.0.1"
---
apiVersion: v1
kind: Pod
metadata: 
  name: h2
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "h2-net1"},
      {"name": "connect-h2"}
    ]'
spec: 
  containers:
  - name: h2
    image: frrouting/frr:v8.1.0
    command:
    - /sbin/init
    securityContext:
      privileged: true
    lifecycle:
          postStart:
            exec:
              command:
                - sh
                - -c
                - "ip link set eth0 down; ip addr add 192.168.1.2/24 dev net1; ip route add default via 192.168.1.1"
---
apiVersion: v1
kind: Pod
metadata: 
  name: r1
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "r1-net1"},
      {"name": "r1-net2"},
      {"name": "connect-r1"}
    ]'
spec: 
  containers:
  - name: r1
    image: frrouting/frr:v8.1.0
    command:
    - /sbin/init
    securityContext:
      privileged: true
    lifecycle:
          postStart:
            exec:
              command:
                - sh
                - -c
                - "ip link set eth0 down;ip addr add 192.168.0.1/24 dev net1;ip addr add 192.168.1.1/24 dev net2"
---
