
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: connect-004e15b6
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "connect",
      "pod-name": "004e15b6",
      "interface": {
        "items": [
          {
            "name": "net1",
            "target-pod-name": "c26a5c65",
            "target-pod-nic": "net1",
            "self-tunnel-id": "7",
            "target-tunnel-id": "6",
            "session-id": "3"
          }
        ]
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: 004e15b6-net1
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "004e15b6-net1",
      "ipam": {
      }
    }
---
apiVersion: v1
kind: Pod
metadata: 
  name: 004e15b6
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "004e15b6-net1"},
      {"name": "connect-004e15b6"}
    ]'
spec: 
  nodeName: sugao-k8s-worker2
  containers:
  - name: 004e15b6
    image: frrouting/frr:v8.1.0
    securityContext:
      privileged: true
    lifecycle:
          postStart:
            exec:
              command:
                - sh
                - -c
                - "ip link set eth0 down"