
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: connect-054ee934
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "connect",
      "pod-name": "054ee934",
      "interface": {
        "items": [
          {
            "name": "net1",
            "target-pod-name": "3d5370c9",
            "target-pod-nic": "net3",
            "self-tunnel-id": "29",
            "target-tunnel-id": "28",
            "session-id": "14"
          }
        ]
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: 054ee934-net1
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "054ee934-net1",
      "ipam": {
      }
    }
---
apiVersion: v1
kind: Pod
metadata: 
  name: 054ee934
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "054ee934-net1"},
      {"name": "connect-054ee934"}
    ]'
spec: 
  nodeName: sugao-k8s-worker2
  containers:
  - name: 054ee934
    image: sugaott/sugaott-ubuntu-focal:1.4
    command: ["bash", "-c", "sleep infinity"]
    securityContext:
      privileged: true
    lifecycle:
          postStart:
            exec:
              command:
                - sh
                - -c
                - "ip link set eth0 down"