
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: connect-1a6cb5a9
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "connect",
      "pod-name": "1a6cb5a9",
      "interface": {
        "items": [
          {
            "name": "net1",
            "target-pod-name": "28385261",
            "target-pod-nic": "net1",
            "self-tunnel-id": "35",
            "target-tunnel-id": "34",
            "session-id": "17"
          }
        ]
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: 1a6cb5a9-net1
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "1a6cb5a9-net1",
      "ipam": {
      }
    }
---
apiVersion: v1
kind: Pod
metadata: 
  name: 1a6cb5a9
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "1a6cb5a9-net1"},
      {"name": "connect-1a6cb5a9"}
    ]'
spec: 
  nodeName: sugao-k8s-worker2
  containers:
  - name: 1a6cb5a9
    image: frrouting/frr:v8.1.0
    securityContext:
      privileged: true
    lifecycle:
          postStart:
            exec:
              command:
                - sh
                - -c
                - "ip link set eth0 down"