
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: connect-1fa5073e
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "connect",
      "pod-name": "1fa5073e",
      "interface": {
        "items": [
        ]
      }
    }
---
apiVersion: v1
kind: Pod
metadata: 
  name: 1fa5073e
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "connect-1fa5073e"}
    ]'
spec: 
  containers:
  - name: 1fa5073e
    image: frrouting/frr:v8.1.0
    securityContext:
      privileged: true
    lifecycle:
          postStart:
            exec:
              command:
                - sh
                - -c
                - "ip link set eth0 down"