
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: connect-2cc617b4
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "connect",
      "pod-name": "2cc617b4",
      "interface": {
        "items": [
          {
            "name": "net1",
            "target-pod-name": "9ddd2539",
            "target-pod-nic": "net2",
            "self-tunnel-id": "9",
            "target-tunnel-id": "8",
            "session-id": "4"
          },
          {
            "name": "net2",
            "target-pod-name": "c3e35308",
            "target-pod-nic": "net1",
            "self-tunnel-id": "12",
            "target-tunnel-id": "13",
            "session-id": "6"
          }
        ]
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: 2cc617b4-net1
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "2cc617b4-net1",
      "ipam": {
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: 2cc617b4-net2
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "2cc617b4-net2",
      "ipam": {
      }
    }
---
apiVersion: v1
kind: Pod
metadata: 
  name: 2cc617b4
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "2cc617b4-net1"},
      {"name": "2cc617b4-net2"},
      {"name": "connect-2cc617b4"}
    ]'
spec: 
  containers:
  - name: 2cc617b4
    image: openshift/openvswitch:v3.9.0
    command:
    - /sbin/init
    securityContext:
      privileged: true
    lifecycle:
          postStart:
            exec:
              command:
                - sh
                - -c
                - "/usr/share/openvswitch/scripts/ovs-ctl start;ip link set eth0 down;ovs-vsctl add-br 2cc617b4;ovs-vsctl add-port 2cc617b4 net1;ovs-vsctl add-port 2cc617b4 net2"