
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: connect-3fdd5048
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "connect",
      "pod-name": "3fdd5048",
      "interface": {
        "items": [
          {
            "name": "net1",
            "target-pod-name": "866dd502",
            "target-pod-nic": "net2",
            "self-tunnel-id": "5",
            "target-tunnel-id": "4",
            "session-id": "2"
          },
          {
            "name": "net2",
            "target-pod-name": "82e8178d",
            "target-pod-nic": "net1",
            "self-tunnel-id": "10",
            "target-tunnel-id": "11",
            "session-id": "5"
          },
          {
            "name": "net3",
            "target-pod-name": "4b37ee6d",
            "target-pod-nic": "net1",
            "self-tunnel-id": "12",
            "target-tunnel-id": "13",
            "session-id": "6"
          }
        ]
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: 3fdd5048-net1
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "3fdd5048-net1",
      "ipam": {
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: 3fdd5048-net2
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "3fdd5048-net2",
      "ipam": {
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: 3fdd5048-net3
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "3fdd5048-net3",
      "ipam": {
      }
    }
---
apiVersion: v1
kind: Pod
metadata: 
  name: 3fdd5048
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "3fdd5048-net1"},
      {"name": "3fdd5048-net2"},
      {"name": "3fdd5048-net3"},
      {"name": "connect-3fdd5048"}
    ]'
spec: 
  containers:
  - name: 3fdd5048
    image: openshift/openvswitch:v3.9.0
    command:
    - /sbin/init
    securityContext:
      privileged: true
    lifecycle:
          postStart:
            exec:
              command:
                - sh
                - -c
                - "/usr/share/openvswitch/scripts/ovs-ctl start;ip link set eth0 down;ovs-vsctl add-br 3fdd5048;ovs-vsctl add-port 3fdd5048 net1;ovs-vsctl add-port 3fdd5048 net2;ovs-vsctl add-port 3fdd5048 net3"