
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: connect-54f93172
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "connect",
      "pod-name": "54f93172",
      "interface": {
        "items": [
          {
            "name": "net1",
            "target-pod-name": "dbc1042c",
            "target-pod-nic": "net1",
            "self-tunnel-id": "29",
            "target-tunnel-id": "28",
            "session-id": "14"
          },
          {
            "name": "net2",
            "target-pod-name": "818530db",
            "target-pod-nic": "net1",
            "self-tunnel-id": "30",
            "target-tunnel-id": "31",
            "session-id": "15"
          },
          {
            "name": "net3",
            "target-pod-name": "febce33a",
            "target-pod-nic": "net1",
            "self-tunnel-id": "32",
            "target-tunnel-id": "33",
            "session-id": "16"
          },
          {
            "name": "net4",
            "target-pod-name": "5d96967c",
            "target-pod-nic": "net1",
            "self-tunnel-id": "34",
            "target-tunnel-id": "35",
            "session-id": "17"
          }
        ]
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: 54f93172-net1
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "54f93172-net1",
      "ipam": {
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: 54f93172-net2
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "54f93172-net2",
      "ipam": {
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: 54f93172-net3
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "54f93172-net3",
      "ipam": {
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: 54f93172-net4
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "54f93172-net4",
      "ipam": {
      }
    }
---
apiVersion: v1
kind: Pod
metadata: 
  name: 54f93172
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "54f93172-net1"},
      {"name": "54f93172-net2"},
      {"name": "54f93172-net3"},
      {"name": "54f93172-net4"},
      {"name": "connect-54f93172"}
    ]'
spec: 
  nodeName: sugao-k8s-worker2
  containers:
  - name: 54f93172
    image: openshift/openvswitch:v3.9.0
    command:
    - /sbin/init
    securityContext:
      privileged: true
    lifecycle:
          postStart:
            exec:
              command:
                - sh
                - -c
                - "/usr/share/openvswitch/scripts/ovs-ctl start;ip link set eth0 down;ovs-vsctl add-br 54f93172;ovs-vsctl add-port 54f93172 net1;ovs-vsctl add-port 54f93172 net2;ovs-vsctl add-port 54f93172 net3;ovs-vsctl add-port 54f93172 net4"