
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: connect-70516687
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "connect",
      "pod-name": "70516687",
      "interface": {
        "items": [
          {
            "name": "net1",
            "target-pod-name": "7f6d27b8",
            "target-pod-nic": "net1",
            "self-tunnel-id": "15",
            "target-tunnel-id": "14",
            "session-id": "7"
          }
        ]
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: 70516687-net1
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "70516687-net1",
      "ipam": {
      }
    }
---
apiVersion: v1
kind: Pod
metadata: 
  name: 70516687
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "70516687-net1"},
      {"name": "connect-70516687"}
    ]'
spec: 
  nodeName: sugao-k8s-worker2
  containers:
  - name: 70516687
    image: frrouting/frr:v8.1.0
    securityContext:
      privileged: true
    lifecycle:
          postStart:
            exec:
              command:
                - sh
                - -c
                - "ip link set eth0 down"