
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: connect-7835e1f2
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "connect",
      "pod-name": "7835e1f2",
      "interface": {
        "items": [
        ]
      }
    }
---
apiVersion: v1
kind: Pod
metadata: 
  name: 7835e1f2
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "connect-7835e1f2"}
    ]'
spec: 
  nodeName: sugao-k8s-worker2
  containers:
  - name: 7835e1f2
    image: frrouting/frr:v8.1.0
    securityContext:
      privileged: true
    lifecycle:
          postStart:
            exec:
              command:
                - sh
                - -c
                - "ip link set eth0 down"