
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: connect-8be0772f
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "connect",
      "pod-name": "8be0772f",
      "interface": {
        "items": [
          {
            "name": "net1",
            "target-pod-name": "d1e0679f",
            "target-pod-nic": "net1",
            "self-tunnel-id": "12",
            "target-tunnel-id": "13",
            "session-id": "6"
          },
          {
            "name": "net2",
            "target-pod-name": "d922f41a",
            "target-pod-nic": "net2",
            "self-tunnel-id": "37",
            "target-tunnel-id": "36",
            "session-id": "18"
          },
          {
            "name": "net3",
            "target-pod-name": "dbc1042c",
            "target-pod-nic": "net2",
            "self-tunnel-id": "40",
            "target-tunnel-id": "41",
            "session-id": "20"
          }
        ]
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: 8be0772f-net1
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "8be0772f-net1",
      "ipam": {
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: 8be0772f-net2
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "8be0772f-net2",
      "ipam": {
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: 8be0772f-net3
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "8be0772f-net3",
      "ipam": {
      }
    }
---
apiVersion: v1
kind: Pod
metadata: 
  name: 8be0772f
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "8be0772f-net1"},
      {"name": "8be0772f-net2"},
      {"name": "8be0772f-net3"},
      {"name": "connect-8be0772f"}
    ]'
spec: 
  nodeName: sugao-k8s-worker2
  containers:
  - name: 8be0772f
    image: frrouting/frr:v8.1.0
    securityContext:
      privileged: true
    lifecycle:
          postStart:
            exec:
              command:
                - sh
                - -c
                - "ip link set eth0 down"