
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: connect-a28e8cd8
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "connect",
      "pod-name": "a28e8cd8",
      "interface": {
        "items": [
          {
            "name": "net1",
            "target-pod-name": "aaa2b5ae",
            "target-pod-nic": "net1",
            "self-tunnel-id": "37",
            "target-tunnel-id": "36",
            "session-id": "18"
          }
        ]
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: a28e8cd8-net1
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "a28e8cd8-net1",
      "ipam": {
      }
    }
---
apiVersion: v1
kind: Pod
metadata: 
  name: a28e8cd8
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "a28e8cd8-net1"},
      {"name": "connect-a28e8cd8"}
    ]'
spec: 
  nodeName: sugao-k8s-worker2
  containers:
  - name: a28e8cd8
    image: frrouting/frr:v8.1.0
    securityContext:
      privileged: true
    lifecycle:
          postStart:
            exec:
              command:
                - sh
                - -c
                - "ip link set eth0 down"