
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: connect-b362ddaa
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "connect",
      "pod-name": "b362ddaa",
      "interface": {
        "items": [
          {
            "name": "net1",
            "target-pod-name": "77c9a676",
            "target-pod-nic": "net3",
            "self-tunnel-id": "15",
            "target-tunnel-id": "14",
            "session-id": "7"
          }
        ]
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: b362ddaa-net1
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "b362ddaa-net1",
      "ipam": {
      }
    }
---
apiVersion: v1
kind: Pod
metadata: 
  name: b362ddaa
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "b362ddaa-net1"},
      {"name": "connect-b362ddaa"}
    ]'
spec: 
  containers:
  - name: b362ddaa
    image: sugaott/sugaott-ubuntu-focal:1.4
    command: ["bash", "-c", "sleep infinity"]
    securityContext:
      privileged: true
    lifecycle:
          postStart:
            exec:
              command:
                - sh
                - -c
                - "ip link set eth0 down"