
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: connect-c7d351ce
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "connect",
      "pod-name": "c7d351ce",
      "interface": {
        "items": [
          {
            "name": "net1",
            "target-pod-name": "3911b5cc",
            "target-pod-nic": "net1",
            "self-tunnel-id": "2",
            "target-tunnel-id": "3",
            "session-id": "1"
          }
        ]
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: c7d351ce-net1
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "c7d351ce-net1",
      "ipam": {
      }
    }
---
apiVersion: v1
kind: Pod
metadata: 
  name: c7d351ce
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "c7d351ce-net1"},
      {"name": "connect-c7d351ce"}
    ]'
spec: 
  containers:
  - name: c7d351ce
    image: frrouting/frr:v8.1.0
    securityContext:
      privileged: true
    lifecycle:
          postStart:
            exec:
              command:
                - sh
                - -c
                - "ip link set eth0 down"