
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: connect-f35fa47e
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "connect",
      "pod-name": "f35fa47e",
      "interface": {
        "items": [
          {
            "name": "net1",
            "target-pod-name": "788fca7e",
            "target-pod-nic": "net1",
            "self-tunnel-id": "18",
            "target-tunnel-id": "19",
            "session-id": "9"
          },
          {
            "name": "net2",
            "target-pod-name": "6363236e",
            "target-pod-nic": "net1",
            "self-tunnel-id": "20",
            "target-tunnel-id": "21",
            "session-id": "10"
          },
          {
            "name": "net3",
            "target-pod-name": "30d08891",
            "target-pod-nic": "net1",
            "self-tunnel-id": "22",
            "target-tunnel-id": "23",
            "session-id": "11"
          },
          {
            "name": "net4",
            "target-pod-name": "c25f6c5c",
            "target-pod-nic": "net2",
            "self-tunnel-id": "39",
            "target-tunnel-id": "38",
            "session-id": "19"
          }
        ]
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: f35fa47e-net1
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "f35fa47e-net1",
      "ipam": {
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: f35fa47e-net2
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "f35fa47e-net2",
      "ipam": {
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: f35fa47e-net3
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "f35fa47e-net3",
      "ipam": {
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: f35fa47e-net4
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "f35fa47e-net4",
      "ipam": {
      }
    }
---
apiVersion: v1
kind: Pod
metadata: 
  name: f35fa47e
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "f35fa47e-net1"},
      {"name": "f35fa47e-net2"},
      {"name": "f35fa47e-net3"},
      {"name": "f35fa47e-net4"},
      {"name": "connect-f35fa47e"}
    ]'
spec: 
  nodeName: sugao-k8s-worker2
  containers:
  - name: f35fa47e
    image: openshift/openvswitch:v3.9.0
    command:
    - /sbin/init
    securityContext:
      privileged: true
    lifecycle:
          postStart:
            exec:
              command:
                - sh
                - -c
                - "/usr/share/openvswitch/scripts/ovs-ctl start;ip link set eth0 down;ovs-vsctl add-br f35fa47e;ovs-vsctl add-port f35fa47e net1;ovs-vsctl add-port f35fa47e net2;ovs-vsctl add-port f35fa47e net3;ovs-vsctl add-port f35fa47e net4"