
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: connect-f8a1755c
spec:
  config: >
    {
      "cniVersion": "0.3.0",
      "type": "connect",
      "pod-name": "f8a1755c",
      "interface": {
        "items": [
        ]
      }
    }
---
apiVersion: v1
kind: Pod
metadata: 
  name: f8a1755c
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "connect-f8a1755c"}
    ]'
spec: 
  nodeName: sugao-k8s-worker2
  containers:
  - name: f8a1755c
    image: sugaott/sugaott-ubuntu-focal:1.4
    command: ["bash", "-c", "sleep infinity"]
    securityContext:
      privileged: true
    lifecycle:
          postStart:
            exec:
              command:
                - sh
                - -c
                - "ip link set eth0 down"