apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-pod
      image: bash
      command: ["echo"]
      args:
        - "${NAME}"
      env:
        - name: NAME
          value: "genzouw"
